### ISSUE TITLE
Unable to play the character

### ISSUE THREAD

**Issue by SirHaesslich** [ReinaSHSL/Yohane-#4]
When clicking "Embark", the game starts the Ironclad run instead. Searching the logs revealed this:

17:07:57.549 INFO dungeons.AbstractDungeon> Generating seeds: 4481565571687500695
17:07:58.544 INFO basemod.BaseMod> publishPreStartGame
17:07:58.549 INFO basemod.BaseMod> hooking into character creation
17:07:58.553 INFO basemod.BaseMod> creating character FallenAngel
17:07:58.745 INFO unlock.UnlockTracker> Already seen: Yohane:AngelWings
17:07:58.796 INFO unlock.UnlockTracker> Already seen: Yohane:AngelWings
17:07:58.812 INFO unlock.UnlockTracker> Already seen: Yohane:AngelWings
17:07:58.814 INFO unlock.UnlockTracker> Already seen: Yohane:AngelWings
17:07:58.967 ERROR basemod.BaseMod> could not instantiate yohanemod.Yohane with the constructor yohanemod.Yohane
17:07:59.474 INFO basemod.BaseMod> running as the Ironclad instead
17:08:00.480 ERROR basemod.BaseMod> error was: null

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at basemod.BaseMod.createCharacter(BaseMod.java:1558)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.CreateCharacterSwitch.Insert(CreateCharacterSwitch.java:32)
	at com.megacrit.cardcrawl.core.CardCrawlGame.createCharacter(CardCrawlGame.java:1279)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:831)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:465)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.core.Settings.dailyModsEnabled()Z
	at yohanemod.Yohane.<init>(Yohane.java:30)
	... 11 more17:08:01.999 INFO basemod.BaseMod> postCreateStartingDeck for: IRONCLAD

The Friendly Minions mod is installed and included

**Comment by SilentJ28** [comment]
@ReinaSHSL Fixed by simply removing the dailymods handing portion of the constructor: https://github.com/SilentJ28/Yohane-/pull/1

**Comment by SilentJ28** [comment]
@SirHaesslich If you want the .jar I built locally while waiting for the real release https://github.com/SilentJ28/Yohane-/releases/tag/1.0.0.1

**Comment by SirHaesslich** [comment]
Thank you.<div id="DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br /> <table
style="border-top: 1px solid #D3D4DE;">
	<tr>
      <td style="width: 55px; padding-top: 18px;"><a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank"><img
src="https://ipmcdn.avast.com/images/icons/icon-envelope-tick-round-orange-animated-no-repeat-v1.gif"
alt="" width="46" height="29" style="width: 46px; height: 29px;"
/></a></td>
		<td style="width: 470px; padding-top: 17px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Без вирусов. <a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank" style="color: #4453ea;">www.avast.ru</a> 		</td>
	</tr>
</table>
<a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1"></a></div>

2018-09-30 3:00 GMT+03:00, SilentJ28 <notifications@github.com>:
